### ISSUE TITLE
 چگونه با یک طراح گرافیک یا طراح وب کار کنیم

### ISSUE THREAD

**Issue by zoghal** [reyhoun/ui.toread#10]
مطلب خوبی هست.
http://mojtaba-taheri.ir/%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%D8%B7%D8%B1%D8%A7%D8%AD-%DA%AF%D8%B1%D8%A7%D9%81%DB%8C%DA%A9/#comment-31

**Comment by navidkashani** [comment]
ممنون صالح جان. منتها مطلب خیلی قدیمی هست و هفته نامه فقط مطالب منتشر شده در هفته اخیر رو لینک می ده

**Comment by zoghal** [comment]
اا به این موضوع دقت نکردم. پوزش
