### ISSUE TITLE
با ++C توسعه دهنده PHP شوید (قسمت اول)

### ISSUE THREAD

**Issue by saderi** [reyhoun/ui.toread#18]
http://hive.ir/tyQBqY

Tags: PHP, C++, PHP-CPP

**Comment by parhumm** [comment]
ممنون از لینک شما اما مقالات مربوط به برنامه نویسی در این خبرنامه نمی‌تواند قرار گیرد. برای اطلاعات بیشتر نگاهی به لینک زیر بیاندازید:
[http://ui.toread.ir/contributing/](http://ui.toread.ir/contributing/)
