### ISSUE TITLE
ساخت اپلیکیشن‌های کلاینتی با انگولار جی‌اس

### ISSUE THREAD

**Issue by 9px** [reyhoun/ui.toread#2]
http://9px.ir/note/build-client-mvc-application-with-angularjs/

**Comment by navidkashani** [comment]
سلام علیرضا جان

لینک ارسالی مربوط به چهارشنبه هفته پیش هست و با توجه به زمان قابل ارائه در خبرنامه شماره سوم که از پنج شنبه شروع می شود، نمی باشد.

با تشکر از همراهی
