### ISSUE TITLE
wireframe  و prototype و  mockup چه فرقي با هم  دارند؟

### ISSUE THREAD

**Issue by mmdsharifi** [reyhoun/ui.toread#30]
http://roocket.ir/articles/wireframe--%D8%8C-prototype-%D8%8C--mockup-%DA%86%D9%87-%D8%AA%D9%81%D8%A7%D9%88%D8%AA%DB%8C-%D8%A8%D8%A7-%D9%87%D9%85-%D8%AF%D8%A7%D8%B1%D9%86%D8%AF-%D8%9F/
## 

Mohammad Sharifi

**Comment by navidkashani** [comment]
ممنون... به هفته نامه شماره 5 اضافه شد
d3ebef2869a7eec2e8b601c31c4c7bc91b7b4a29
