### ISSUE TITLE
CSS نویسی بی قاعده با SASS

### ISSUE THREAD

**Issue by mahdialikhasi** [reyhoun/ui.toread#39]
http://noisy.ir/blogs/view/Sass-و-compass-–-استایل-هایتان-را-متفاوت-بنویسید

Tags:css, sass

**Comment by navidkashani** [comment]
ممنون مهدی جان بابت ارسال لینک ها. منتها من پیشنهاد می کنم یک بار با دقت صفحه پیشنهاد لینک را مطالعه کنی:
http://ui.toread.ir/contributing/

چند مورد مهم:
- لینک ها باید تنها مرتبط با حوزه طراحی وب باشند. بطور مثال مطالب پی اچ پی و برنامه نویسی در اینجا قرار نمی گیرد
- مطالب باید در طول هفته گذشته ارسال شده باشند

من مواردی را که دارای اشکال هست می بندم

با تشکر
