### ISSUE TITLE
طراحی وب واکنشی

### ISSUE THREAD

**Issue by 9px** [reyhoun/ui.toread#5]
http://9px.ir/note/responsive-web-design

**Comment by parhumm** [comment]
ممنون از لینک پیشهادی اما متاسفانه این لینک را در خبرنامه نمی‌توانیم قرار دهیم.
مطلب قدیمی هست و خیلی از لینک‌ها یا از بین رفتن یا فریم ورک های قدیمی هستن که دیگر کاربرد ندارند.

بعضی لینک‌ها که مشکل داشتند:
- http://978.gs/
- http://csshor.us/
- http://jhough10.github.io/Centurion/index.html
- http://groundwork.sidereel.com/

پیشنهاد میکنم تحت عنوان یک مطلب جدید به بررسی فریمورک ها و تکنیک‌های بروز ریسپانسیو بپردازید.

با تشکر
