### ISSUE TITLE
نصب و راه اندازی gulp-bootstrap-sass

### ISSUE THREAD

**Issue by mmdsharifi** [reyhoun/ui.toread#51]
http://www.baboon.ir/%D8%B1%D8%A7%D9%87-%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-bootstrap-sass%D8%8C-bower%D8%8C-gulp-%D9%88-fontawesome/

**Comment by navidkashani** [comment]
Thanks, added to issue 15
