### ISSUE TITLE
بوت استرپ فارسی راستچین شده نسخه 4

### ISSUE THREAD

**Issue by mmdsharifi** [reyhoun/ui.toread#65]
http://bootstrap.gigfa.com/%D8%A8%D9%88%D8%AA-%D8%A7%D8%B3%D8%AA%D8%B1%D9%BE-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%B1%D8%A7%D8%B3%D8%AA%DA%86%DB%8C%D9%86-%D8%B4%D8%AF%D9%87-%D9%86%D8%B3%D8%AE%D9%87-4/

**Comment by imanYusefzadeh** [comment]
Thanks so much
