### ISSUE TITLE
کدنویسی را با uilang شروع کنید

### ISSUE THREAD

**Issue by saderi** [reyhoun/ui.toread#8]
http://hive.ir/BrZrbV
Tag: uilang

**Comment by navidkashani** [comment]
ممنون پیام جان

برای لینک ارسال کننده چه لینکی را قرار دهیم؟ توییتر؟  وبلاگ؟

**Comment by saderi** [comment]
لینک وبلاگ رو قرار بدید ممنون میشم

**Comment by navidkashani** [comment]
Added to Issue 3 6a1cc6b6ab266524dff456cd5ee5f3af5d13f554
